export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import "@/styles/globals.css"
import { ThemeProvider } from "@/components/theme-provider"
import Navigation from "@/components/marketing/navigation"
import { Footer } from "@/components/marketing/landing/sections/footer"

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navigation />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
