export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import "@/styles/globals.css"
import Navigation from "@/components/marketing/navigation"
import { Footer } from "@/components/marketing/landing/sections/footer"

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  )
}
