import Content from "@/components/layout/content"

export const metadata = {
    title: 'Settings',
    description: 'Generated by Next.js',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <Content className="md:p-4 px-2 scroll-auto overflow-y-auto">
            {children}
        </Content>
    )
}