services:
  scheduler:
    build: .
    container_name: scheduler
    restart: always
    environment:
      - WHATSAPP_API_ENDPOINT=
      - DB_HOST=
      - DB_PORT=
      - DB_NAME=
      - DB_USER=
      - DB_PASSWORD=
