import { RecentChats } from "@/components/chat/recent-chats";
import { contactRepository } from "@/Nenichat/Contacts/infra/persistance/ContactRepository"
import IContactWithLastMessage from "@/Nenichat/Contacts/app/dtos/IContactWithLastMessage"
import Content from "@/components/layout/content";
import { GoWappChatRepository } from "@/Nenichat/Chats/infra/api"
import { IChat } from "@/Nenichat/Chats/domain/IChat";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { PageHeader } from "@/components/ui/page-header";
import { EmptyChats } from "@/components/chat/empty-chats";

export const metadata = {
  title: 'Chats',
  description: 'Generated by Next.js',
}

export default async function ChatLayout({
  children,
}: {
  children: React.ReactNode
}) {
  let contactsWithLastMessage: IChat[] = [];
  try {
    const supabase = await createServerSupabaseClient();
    const { data: { user }, error: userError } = await supabase.auth.getUser();

    if (userError) console.error(userError)

    // what business' contacts to retrieve
    const { data: business, error: businessError } = await supabase
      .from("business")
      .select("id")
      .eq("owner_id", user?.id)
      .single();

    if (businessError) console.error(businessError)

    if (!business) {
      throw new Error("No tienes un negocio");
    }

    const { data: containerData, error: containerError } = await supabase
      .from("whatsapp-containers")
      .select("*")
      .eq("business_id", business.id)
      .single();

    if (containerError) console.error(containerError)

    if (!containerData) {
      return <Content>
        <PageHeader title="" />
        <EmptyChats />
      </Content>
    }

    let url = "http://192.168.1.64" + "/api/user" + "/" + business.id
    const wappChatRepository = new GoWappChatRepository(url, "admin", "admin")
    // contactsWithLastMessage = await contactRepository.getContactsWithLastMessage(0, 1000);
    contactsWithLastMessage = await wappChatRepository.list(0, 26)
    console.log(contactsWithLastMessage)
  } catch (error) {
    console.warn("Failed to fetch contacts in RootLayout (possibly during build):", error);
  }
  const contactsWithLastMessageJSON = JSON.stringify(contactsWithLastMessage)
  return (
    <Content className="flex flex-col md:flex-row">
      <RecentChats
        className="w-full md:max-w-52 lg:max-w-xs md:border-r"
        contacts={contactsWithLastMessageJSON} />
      <div className="flex-1 overflow-hidden bg-background">
        {children}
      </div>
    </Content>
  )
}
