-- For now we will not care about groups, only on-to-one chats.

CREATE TABLE chats (
    id BIGSERIAL PRIMARY KEY REFERENCES contacts(id) ON DELETE CASCADE, -- the chat.id generated by our database
    -- chat_jid TEXT NOT NULL UNIQUE,
    -- Group-specific attributes (nullable for one-to-one chats)
    -- group_name TEXT,
    -- group_description TEXT,
    -- group_owner_id BIGINT REFERENCES contacts(id) ON DELETE SET NULL,
    is_group BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);